In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import seaborn as sns

## Data Preprocessing

## Training Data 

In [6]:
training_set= tf.keras.utils.image_dataset_from_directory(
    'train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(256, 256),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)


Found 70295 files belonging to 38 classes.


### Validation Data

In [7]:
validation_set= tf.keras.utils.image_dataset_from_directory(
    'valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(256, 256),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

Found 17572 files belonging to 38 classes.


In [11]:
for x,y in training_set:
    print (x, x.shape)
    print (y, y.shape)
    break

tf.Tensor(
[[[[ 73. 129. 100.]
   [ 70. 126.  97.]
   [ 68. 125.  93.]
   ...
   [126. 181. 150.]
   [129. 184. 152.]
   [119. 174. 142.]]

  [[ 67. 123.  94.]
   [ 69. 125.  96.]
   [ 71. 128.  96.]
   ...
   [125. 180. 149.]
   [124. 179. 147.]
   [117. 172. 140.]]

  [[ 59. 115.  86.]
   [ 65. 121.  92.]
   [ 71. 128.  96.]
   ...
   [134. 189. 158.]
   [127. 182. 150.]
   [127. 182. 150.]]

  ...

  [[ 74. 131.  88.]
   [ 75. 132.  87.]
   [ 78. 136.  88.]
   ...
   [100. 159. 103.]
   [ 91. 149. 101.]
   [ 90. 147. 102.]]

  [[ 72. 129.  88.]
   [ 73. 130.  87.]
   [ 75. 132.  87.]
   ...
   [ 93. 152.  96.]
   [ 84. 142.  94.]
   [ 83. 140.  95.]]

  [[ 71. 128.  87.]
   [ 71. 128.  85.]
   [ 72. 129.  86.]
   ...
   [ 91. 150.  94.]
   [ 81. 139.  91.]
   [ 80. 137.  92.]]]


 [[[129. 123. 127.]
   [114. 108. 112.]
   [119. 113. 117.]
   ...
   [142. 135. 143.]
   [142. 135. 143.]
   [140. 133. 141.]]

  [[117. 111. 115.]
   [111. 105. 109.]
   [121. 115. 119.]
   ...
   [141. 1

## Model Building

In [6]:
from tensorflow.keras.layers import Dense,Conv2D,MaxPool2D,Flatten
from tensorflow.keras.models import Sequential

In [5]:
model = Sequential()

### Building Convolution Layer


In [7]:
model.add(Conv2D(filters = 32,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters = 32,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [8]:
model.add(Conv2D(filters = 62,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters = 62,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [9]:
model.add(Conv2D(filters = 128,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters = 128,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [10]:
model.add(Conv2D(filters = 256,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters = 256,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [11]:
model.add(Flatten())

In [12]:
model.add(Dense(units=1024,activation='relu'))

In [13]:
# Output Layer
model.add(Dense(units=38,activation='softmax'))

### Compiling Model

In [14]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [18]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 128, 128, 32)      896       
                                                                 
 conv2d_1 (Conv2D)           (None, 128, 128, 32)      9248      
                                                                 
 max_pooling2d (MaxPooling2D  (None, 64, 64, 32)       0         
 )                                                               
                                                                 
 conv2d_2 (Conv2D)           (None, 64, 64, 62)        17918     
                                                                 
 conv2d_3 (Conv2D)           (None, 64, 64, 62)        34658     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 32, 32, 62)       0         
 2D)                                                  