In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import seaborn as sns

## Data Preprocessing

## Training Data 

In [26]:
training_set= tf.keras.utils.image_dataset_from_directory(
    'train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)


Found 70295 files belonging to 38 classes.


### Validation Data

In [27]:
validation_set= tf.keras.utils.image_dataset_from_directory(
    'valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

Found 17572 files belonging to 38 classes.


In [28]:
for x,y in training_set:
    print (x, x.shape)
    print (y, y.shape)
    break

tf.Tensor(
[[[[213.25 205.25 218.25]
   [217.25 209.25 222.25]
   [217.   209.   222.  ]
   ...
   [192.   186.   198.  ]
   [201.75 195.75 207.75]
   [210.   204.   216.  ]]

  [[208.   200.   213.  ]
   [209.25 201.25 214.25]
   [218.25 210.25 223.25]
   ...
   [211.25 205.25 217.25]
   [216.5  210.5  222.5 ]
   [211.5  205.5  217.5 ]]

  [[205.   197.   210.  ]
   [204.25 196.25 209.25]
   [213.75 205.75 218.75]
   ...
   [201.75 195.75 207.75]
   [222.   216.   228.  ]
   [199.75 193.75 205.75]]

  ...

  [[126.   118.   133.  ]
   [104.5   96.5  111.5 ]
   [116.75 108.75 123.75]
   ...
   [132.25 124.25 145.25]
   [128.   120.   141.  ]
   [121.   113.   134.  ]]

  [[130.5  122.5  137.5 ]
   [123.5  115.5  130.5 ]
   [114.5  106.5  121.5 ]
   ...
   [124.75 116.75 137.75]
   [121.5  113.5  134.5 ]
   [123.75 115.75 136.75]]

  [[113.75 105.75 120.75]
   [123.5  115.5  130.5 ]
   [116.5  108.5  123.5 ]
   ...
   [130.5  122.5  143.5 ]
   [122.75 114.75 135.75]
   [132.25 124.25 14

## Model Building

### To avoid overshooting:
1.decrease learning rate,default is 0.001 we are using 0.0001
2.increasing no. of neurons to avoid underfitting, add more convolution layer to extract more feature.

In [44]:
from tensorflow.keras.layers import Dense,Conv2D,MaxPool2D,Flatten,Dropout
from tensorflow.keras.models import Sequential

In [45]:
model = Sequential()

### Building Convolution Layer


In [46]:
model.add(Conv2D(filters = 32,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters = 32,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [47]:
model.add(Conv2D(filters = 62,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters = 62,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [48]:
model.add(Conv2D(filters = 128,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters = 128,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [49]:
model.add(Conv2D(filters = 256,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters = 256,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [50]:
model.add(Conv2D(filters = 512,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters = 512,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [51]:
model.add(Dropout(0.25)) #to avoid overfitting

In [52]:
model.add(Flatten())

In [53]:
model.add(Dense(units=1500,activation='relu'))

In [54]:
model.add(Dropout(0.4))

In [55]:
# Output Layer
model.add(Dense(units=38,activation='softmax'))

### Compiling Model

In [56]:
model.compile(optimizer=tf.keras.optimizers.Adam(
    learning_rate=0.0001),loss='categorical_crossentropy',metrics=['accuracy'])

In [57]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_16 (Conv2D)          (None, 128, 128, 32)      896       
                                                                 
 conv2d_17 (Conv2D)          (None, 126, 126, 32)      9248      
                                                                 
 max_pooling2d_8 (MaxPooling  (None, 63, 63, 32)       0         
 2D)                                                             
                                                                 
 conv2d_18 (Conv2D)          (None, 63, 63, 62)        17918     
                                                                 
 conv2d_19 (Conv2D)          (None, 61, 61, 62)        34658     
                                                                 
 max_pooling2d_9 (MaxPooling  (None, 30, 30, 62)       0         
 2D)                                                  

## Training the Model

In [58]:
training_history = model.fit(x=training_set,validation_data = validation_set,epochs=10)

Epoch 1/10
2197/2197 [==============================] - 223s 100ms/step - loss: 1.3058 - accuracy: 0.6124 - val_loss: 0.5465 - val_accuracy: 0.8293
Epoch 2/10
2197/2197 [==============================] - 200s 91ms/step - loss: 0.4421 - accuracy: 0.8604 - val_loss: 0.2862 - val_accuracy: 0.9106
Epoch 3/10
2197/2197 [==============================] - 195s 89ms/step - loss: 0.2623 - accuracy: 0.9147 - val_loss: 0.2047 - val_accuracy: 0.9361
Epoch 4/10
2197/2197 [==============================] - 195s 89ms/step - loss: 0.1797 - accuracy: 0.9421 - val_loss: 0.1567 - val_accuracy: 0.9502
Epoch 5/10
2197/2197 [==============================] - 196s 89ms/step - loss: 0.1389 - accuracy: 0.9548 - val_loss: 0.1360 - val_accuracy: 0.9569
Epoch 6/10
2197/2197 [==============================] - 196s 89ms/step - loss: 0.1089 - accuracy: 0.9648 - val_loss: 0.1450 - val_accuracy: 0.9544
Epoch 7/10
2197/2197 [==============================] - 193s 88ms/step - loss: 0.0894 - accuracy: 0.9703 - val_loss: 

### Model Evaluation

In [61]:
#model evaluation on training_set
train_loss,train_acc = model.evaluate(training_set)

2197/2197 [==============================] - 88s 40ms/step - loss: 0.0504 - accuracy: 0.9833


In [62]:
print(train_loss,train_acc)

0.050378791987895966 0.9832847118377686


In [63]:
#model evaluation on validation_set
val_loss,val_acc = model.evaluate(validation_set)

550/550 [==============================] - 32s 57ms/step - loss: 0.1492 - accuracy: 0.9555


In [64]:
print(val_loss,val_acc)

0.14921829104423523 0.9554973840713501


### Saving the model

In [66]:
model.save("trained_model.keras")